# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=500, verbose_name='\u4f5c\u8005'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=500, verbose_name='\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='intro',
            field=models.CharField(blank=True, max_length=500, verbose_name='\u94fe\u63a5'),
        ),
        migrations.AlterField(
            model_name='zxfc',
            name='title',
            field=models.CharField(max_length=500, verbose_name='\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='zxfc',
            name='url',
            field=models.CharField(max_length=500, verbose_name='\u94fe\u63a5'),
        ),
    ]
